name: Check Copywrite Headers

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  copywrite:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
        name: Setup Copywrite
        with:
          version: v0.24.2
          archive-checksum: 11d1ade39293c45b3ec705c68453aff39d1588913eee7cc8f646f11f548dc35c
      - name: Check Header Compliance
        run: copywrite headers --plan
permissions:
  contents: read